# Starter pipeline
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'dockertest'
    dockerComposeFile: '**/Dockerfile'
    projectName: '- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'dockertestreg'
    dockerComposeFile: '**/Dockerfile'
    projectName: 'bassine/angulardemodevops:$(Build)'
    action: 'Push services'
    action: 'Run services'

  inputs:
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: '**/Dockerfile'
    projectName: 'bassine/angulardemodevops:$(Build)'
    action: 'Build services'